#pragma once

DECLARE_DELEGATE_OneParam(MoveForwardDelegate, float)
DECLARE_DELEGATE_OneParam(MoveRightDelegate, float)
DECLARE_DELEGATE_TwoParams(LookDelegate, float, float)
DECLARE_DELEGATE(CrouchPressDelegate)
DECLARE_DELEGATE(CrouchReleaseDelegate)
DECLARE_DELEGATE(JumpPressDelegate)
DECLARE_DELEGATE(JumpReleaseDelegate)
DECLARE_DELEGATE(RunPressDelegate)
DECLARE_DELEGATE(RunReleaseDelegate)
DECLARE_DELEGATE(FlyPressDelegate)
DECLARE_DELEGATE(FlyReleaseDelegate)